apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  namespace: production
  labels:
    app: demo-service
    version: "1.2.3"  # This would be updated by the PR
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
        version: "1.2.3"  # This would be updated by the PR
    spec:
      containers:
      - name: demo-service
        image: your-registry/demo-service:1.2.3  # This is the line that gets updated
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "demo-service"
        - name: VERSION
          value: "1.2.3"  # This would be updated by the PR
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: production
spec:
  selector:
    app: demo-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 